---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: Amazon FSX for ONTAP の新機能をご確認ください。 
---
= Amazon FSX for ONTAP の新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Amazon FSX for ONTAP の新機能をご確認ください。



== 2022 年 2 月 27 日



=== IAM の役割を引き受けます

ONTAP 作業環境向け FSX を作成する場合、 Cloud Manager が ONTAP 作業環境用の FSX を作成すると想定できる IAM ロールの ARN を指定する必要があります。以前は、 AWS アクセスキーを指定する必要がありました。

link:/task/task-setting-up-permissions-fsx.html["FSX for ONTAP のアクセス許可を設定する方法について説明します"]。



== 2021 年 10 月 31 日



=== Cloud Manager API を使用して iSCSI ボリュームを作成

Cloud Manager API を使用して FSX for ONTAP 用の iSCSI ボリュームを作成し、作業環境で管理できます。



=== ボリュームの作成時にボリュームの単位を選択します

可能です link:/task/task-add-fsx-volumes.html#creating-volumes["ボリュームの作成時にボリュームの単位（ GiB または TiB ）を選択します"] FSX for ONTAP の場合。



== 2021 年 10 月 4 日



=== Cloud Manager を使用して CIFS ボリュームを作成

できるようになりました。 link:/task/task-add-fsx-volumes.html#creating-volumes["Cloud Manager を使用して、 FSX for ONTAP に CIFS ボリュームを作成します"]。



=== Cloud Manager を使用してボリュームを編集

できるようになりました。 link:/task/task-manage-fsx-volumes.html#editing-volumes["Cloud Manager を使用して ONTAP ボリュームの FSX を編集します"]。



== 2021 年 9 月 2 日



=== Amazon FSX for ONTAP のサポート

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["ONTAP 対応の Amazon FSX"] は、 NetApp ONTAP ストレージ・オペレーティング・システムを搭載したファイル・システムの起動と実行を可能にするフルマネージド・サービスです。FSX for ONTAP は、ネットアップのお客様がオンプレミスで使用しているのと同じ機能、パフォーマンス、管理機能を、ネイティブの AWS サービスの簡易性、即応性、セキュリティ、拡張性で提供します。
+
link:concept-fsx-aws.html["Amazon FSX for ONTAP の詳細をご覧ください"]。

* ONTAP 作業環境用に Cloud Manager で FSX を設定できます。
+
link:/task/task-creating-fsx-working-environment.html["ONTAP 作業環境用の Amazon FSX を作成します"]。

* AWS と Cloud Manager のコネクタを使用すると、ボリュームの作成と管理、データのレプリケート、および Data Sense や Cloud Sync などのクラウドサービス ONTAP との FSX の統合が可能です。
+
link:task-scanning-fsx.html#quick-start["Amazon FSX for ONTAP のクラウドデータセンスを今すぐ始めましょう"]。


